### ISSUE TITLE
/run/shm/sciond/default.sock is gone

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scion-web#137]
Sometimes we find errors, in particular in the attachment points, where `bwtestserver` is not working correctly. Listing `/run/shm/` shows no `sciond` directory there.
We believe it might be related to systemd removal of IPC: https://superuser.com/a/1179962/541170

We are running a `auditd` in all four APs, started like:
`sudo auditctl -w /run/shm/sciond/  -p wa -k sciondsocketdelete`
You can consult the auditd entries like:
`sudo ausearch -i -k sciondsocketdelete | grep DELETE`

When found, change the machine provisioning to take this into account.

**Comment by mlegner** [comment]
We had a look and figured out that this is indeed related to removal of IPC files due to the fact that SCION is not being run as a system user.
A temporary solution is adding `RemoveIPC=no` to `/etc/systemd/logind.conf` as we do in https://github.com/netsec-ethz/scion-coord/blob/master/scion_install_script.sh (line 220).
A cleaner long-term solution is running SCION as a system user.

**Comment by juagargi** [comment]
Thanks @mlegner and @kormat .
We still have to change the Ansible deployment playbook for SCIONLab. I will close this once we have it done.

**Comment by juagargi** [comment]
This is solved actually in scion-deploy (and not in this project). https://github.com/netsec-ethz/scion-deploy/pull/47
